<?php
/*
 * Implements hook_menu().
 */


function reports_menu(){ 
  $items['reports'] = array(
    'title' => 'Reports page',
    'description' => 'Generate reports.',
    'page callback' => 'reports_function', //_make_bar_chart',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );  

  $items['questions/%ctools_js/%'] = array(
    'page callback' => 'questions_callback',
    'page arguments' => array(1,2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

   $items['ajax_link_callback/graph/%'] = array(
   'page callback' => 'ajax_link_response_graph',
   'page arguments' => array(2),
   'access callback' => 'user_access',
   'access arguments' => array('access content'),
   'type' => MENU_CALLBACK,
  );

   $items['reports_ajax'] = array(
    'page callback' => 'my_module_example',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function my_module_example () {
  return "HI";
}

 
 function ajax_link_response_graph($ajax) {
  if ($ajax) {
   $output = _make_bar_chart();


   
 //  $output = 'Hey ! Some AJAX content !'
 
   $commands = array();
   $commands[] = ajax_command_replace('#myDiv', $output);
   $page = array('#type' => 'ajax', '#commands' => $commands);
   ajax_deliver($page);
  }
 else {
   $output = t("This is some content delivered via a page load.");
   return $output;
 }
}
 

function _make_bar_chart(){
 /* $query = db_select('questions', 'q');
  $results = $query
          ->fields('q')
          ->execute();

  $query = db_select('questions', 'q');
  $count1 = $query
    ->fields('q', array('category'))
    ->condition('q.category', 'lol')
    ->execute()
    ->rowCount(); 

  $query = db_select('questions', 'q');
  $count2 = $query
    ->fields('q', array('category'))
    ->condition('q.category', 'q')
    ->execute()
    ->rowCount(); ○

  $data = array();
 // foreach ($results as $result) {
    array_push($data, $count1);//$result->qid);
    array_push($data, $count2);
  //}
//Get the data into an array of values
//    foreach ($data as $value) {
        //array for pie chart, displaying just the last year
        $pie_data['chart']['pie'] = array(
            'header' => 'Header',
            'rows' => array($data), //the data to display
            'columns' => array('Data'),
            'chartType' => 'PieChart', //does what it says on the tin
            'options' => array(
                'title' => 'QID of Questions',
                'forceIFrame' => FALSE,
                'width' => 150,
                'height' => 200,
               // 'legend' => none, //no legend thanks
               // 'pieSliceText' => none, //stop text from displaying on the pie slices
                'fontSize' => 12,
                'enableInteractivity' => TRUE, //stop mouse overs on pie charts
                'backgroundColor' => 'transparent'
            )
        );
  
    $chart = array(
      '#plugin'    => 'google', // Google Charts API will be used
      '#type'     => 'line2D', // A simple line chart
      '#height'   => 100, // in pixels
      '#width'    => 200, // in pixels

       $values, // This is the contents of the array build above
    );*/
  
    //theme all the charts!
//drupal_add_js(drupal_get_path('module', 'mymodule') . '/jsapi.js');
  //  drupal_add_js(array('charts.js' => array('SOMEVARIABLE' => 'woohoo')), 'setting');
  $testVariable = rand(5, 20);
//drupal_add_js(array('reports' => array('testvar' => $testVariable)), array('type' => 'setting'));
  drupal_add_js(drupal_get_path('module', 'reports') . '/charts.js');
    return theme('reports_chart_template', array('test' => $testVariable));
}

function reports_chart(){
  return "YSSAGANDA";
}
   

function reports_function(){
    //theme all the charts!
  drupal_add_js(drupal_get_path('module', 'reports') . '/jsapi.js');
//  drupal_add_js(drupal_get_path('template', 'reports-chart-page') . '/charts.js');
  return theme('reports_template');
} 
/*
 * Implementation of hook_theme().
 */
function reports_theme(){
  return array(
    'reports_template' => array(
      // template file name will be custom-page.tpl.php
      'template' => 'reports-page',
    ),
    'reports_chart_template' => array(
      // template file name will be custom-page.tpl.php
      'template' => 'reports-chart-page',
    ),
  );
}


/*
function reports_get_by_category_id($cat_id){
  $items = '';
  switch($cat_id){
    case 12: 
     $items = '<ul><li>Product 1</li><li>Product 2</li></ul>';
     break;
    case 20:
     $items = '<ul><li>Product 3</li><li>Product 4</li></ul>';
     break;  
  }
// create a JSON object. The object will contain a property named “products” that will be set with the $items variable. 
  return drupal_json(array('products'=>$items));
  exit;
}

*/
function reports_init() {
  theme('reports_javascript');
}

function theme_reports_javascript() {
  drupal_add_js(drupal_get_path('module', 'reports') . '/charts.js');
}